{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = hasattr('hello', 'check')", "trace": "self = <test_pytest.test_pytest.TestMyClass object at 0x0000023748A63808>\n\n    def test_two(self):\n        x = \"hello\"\n>       assert hasattr(x, \"check\")\nE       AssertionError: assert False\nE        +  where False = hasattr('hello', 'check')\n\ntest_pytest\\test_pytest.py:80: AssertionError"}, "attachments": [{"name": "stdout", "source": "bdf525f2-bf97-4736-b805-fa1f6ee48a40-attachment.txt", "type": "text/plain"}], "start": 1583051668824, "stop": 1583051668824, "uuid": "5a0455df-e95a-4d78-9014-2dc70a81d4c0", "historyId": "8afe24c3debe08db4f2232ad9f364a41", "testCaseId": "3b1b357f1ddfe4f952a75942e4189695", "fullName": "test_pytest.test_pytest.TestMyClass#test_two", "labels": [{"name": "parentSuite", "value": "test_pytest"}, {"name": "suite", "value": "test_pytest"}, {"name": "subSuite", "value": "TestMyClass"}, {"name": "host", "value": "luoluo-PC"}, {"name": "thread", "value": "3032-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest.test_pytest"}]}