{"name": "test_two", "status": "failed", "statusDetails": {"message": "AssertionError: assert False\n +  where False = hasattr('hello', 'check')", "trace": "self = <test_pytest.test_pytest.TestClass object at 0x00000272C6AC7F88>\n\n    def test_two(self):\n        x = \"hello\"\n>       assert hasattr(x, \"check\")\nE       AssertionError: assert False\nE        +  where False = hasattr('hello', 'check')\n\ntest_pytest\\test_pytest.py:43: AssertionError"}, "start": 1583068901786, "stop": 1583068901786, "uuid": "48a6652c-7d6d-473e-b0be-9e766d78b314", "historyId": "1a3b91e14faa07dcdcb8b7ae9ff35c83", "testCaseId": "2814cd1496d73dd219c414a328e4e062", "fullName": "test_pytest.test_pytest.TestClass#test_two", "labels": [{"name": "parentSuite", "value": "test_pytest"}, {"name": "suite", "value": "test_pytest"}, {"name": "subSuite", "value": "TestClass"}, {"name": "host", "value": "luoluo-PC"}, {"name": "thread", "value": "14108-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_pytest.test_pytest"}]}